theme: jekyll-theme-cayman
title: Where To Sell Products (WTSP)
email: luisedof10@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  WTSP is a system to exploit location context and natural language
  to characterize geographic areas according to what people publishes online.

jekyll-spaceship:
    # default enabled processors
    processors:
      - table-processorv