version: "3"
services:
  zeppelin:
    image: ohtar10/zeppelin:0.9.0-SNAPSHOT
    # build:
    #   context: ./images/zeppelin
    container_name: zeppelin
    ports:
      - "8080:8080"
      - "4040:4040"
    environment: 
      - ZEPPELIN_WEBSOCKET_MAX_TEXT_MESSAGE_SIZE=4096000
    volumes:
      - ${WORK_DIR}/notebooks/zeppelin/:/zeppelin/notebook
      - ${WORK_DIR}/datasets/:/zeppelin/datasets
      - ${WORK_DIR}/models/:/zeppelin/models
      - ${WORK_DIR}/software/spark:/usr/lib/spark
      - ${WORK_DIR}/resources/zeppelin/conf/log4j.properties:/zeppelin/conf/log4j.properties
      - ${WORK_DIR}/resources/zeppelin/conf/zeppelin-env.sh:/zeppelin/conf/zeppelin-env.sh
      #- ${WORK_DIR}/resources/zeppelin/conf/interpreter.json:/zeppelin/conf/interpreter.json
    networks:
      - wtsp-net

networks:
  wtsp-net:
    driver: bridge