version: "3"
services:
  wtsp:
    image: ohtar10/wtsp:0.1.1
    container_name: wtsp
    environment: 
      - LC_ALL=C.utf-8
      - LANG=C.utf-8
      - MODIN_OUT_OF_CORE=true
      - MODIN_CPUS=10
      # 60GB
      - MODIN_MEMORY=60000000000
    # Just to avoid letting this container to die.
    command: tail -f /var/log/lastlog
    volumes:
      - ${WORK_DIR}/:/workdir
    networks:
      - wtsp-net
  
networks:
  wtsp-net:
    driver: bridge