version: "3"
services:
  zeppelin:
    image: ohtar10/wtsp:0.1.0
    container_name: wtsp
    environment: 
      - ENV LC_ALL=C.utf-8
      - ENV LANG=C.utf-8
    # Just to avoid letting this container to die.
    command: tail -f /var/log/lastlog
    volumes:
      - ${WORK_DIR}/datasets:/datasets
    networks:
      - wtsp-net
  
networks:
  wtsp-net:
    driver: bridge