name: wtsp-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - fiona=1.8.4
  - flake8=3.7.9
  - folium=0.10.0
  - gdal=2.3.3
  - geopandas=0.4.1
  - geos=3.7.1
  - icu=58.2
  - keras=2.2.4
  - keras-gpu=2.2.4
  - libgdal=2.3.3
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - matplotlib=3.1.1
  - mypy=0.740
  - mypy_extensions=0.4.1
  - nltk=3.4.5
  - numpy-base=1.17.2
  - pandas=0.25.1
  - pip=19.2.3
  - poppler=0.65.0
  - poppler-data=0.4.9
  - pyarrow=0.14.1
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - shapely=1.6.4
  - tensorflow-base=1.12.0
  - pip:
    - absl-py==0.8.0
    - appdirs==1.4.3
    - astor==0.8.0
    - flake8-docstrings==1.5.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.24.1
    - h5py==2.10.0
    - imgkit==1.0.2
    - llvmlite==0.29.0
    - numba==0.45.1
    - numpy==1.17.2
    - opt-einsum==3.1.0
    - protobuf==3.10.0
    - py-cpuinfo==5.0.0
    - pydocstyle==5.0.1
    - pytest-benchmark==3.2.2
    - pytest-mypy==0.4.2
    - snowballstemmer==2.0.0
    - swifter==0.295
    - tensorboard==2.0.0
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.0
    - tensorflow-gpu==2.0.0
    - termcolor==1.1.0
    - uritools==2.2.0
    - urlextract==0.13.0
    - wrapt==1.11.2